//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BamStats.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;
	using System.ComponentModel.DataAnnotations;
    
    public partial class BamFight
    {
        public int Id { get; set; }
        public int Winner { get; set; }
        public int Loser { get; set; }
        public Nullable<bool> Stance { get; set; }

		[DataType(DataType.Date)]
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime FightDate { get; set; }
    
        public virtual BamName BamName { get; set; }
        public virtual BamName BamName1 { get; set; }
    }
}
